# Pages CMS Configuration

content:
  - name: 'pages'
    label: 'Pages'
    path: 'src/content/pages'
    format: 'md'
    schema:
      title: 'String'
      description: 'String'
      updatedDate: 'Date'
      features: 'Array<String>?'
      canonicalUrl: 'String?'
      ogImage: 'String?'
      ogType: 'String?'
      twitterCard: 'String?'
      metaRobots: 'String?'
      keywords: 'Union<String, Array<String>>?'
      author: 'String?'
      hero: 'Object?'
      about: 'Object?'
      services: 'Union<Object, Array<Object>>?'
      testimonials: 'Object?'
      cta: 'Object?'
      articlesSection: 'Object?'
      pricingSection: 'Object?'
      mission: 'Object?'
      values: 'Array<Object>?'
      founders: 'Array<Object>?'
      pageHeader: 'Object?'

  - name: 'articles'
    label: 'Articles'
    path: 'src/content/articles'
    format: 'md'
    schema:
      title: 'String'
      description: 'String'
      publishDate: 'Date'
      updatedDate: 'Date?'
      author: 'String'
      image: 'String?'
      featured: 'Boolean'
      categories: 'Array<String>?'
      tags: 'Array<String>?'
      canonicalUrl: 'String?'
      ogImage: 'String?'
      ogType: 'String?'
      twitterCard: 'String?'
      metaRobots: 'String?'

media:
  - name: 'images'
    label: 'Images'
    path: 'src/assets/images'

  - name: 'icons'
    label: 'Icons'
    path: 'src/assets/icons'

  - name: 'assets'
    label: 'Other Assets'
    path: 'src/assets'
