media:
  input: src/assets
  output: assets

content:
  # [Previous home, about, and services configurations remain the same]

  - name: 'articles'
    label: 'Articles & Resources'
    type: 'file'
    path: 'src/content/pages/articles.md'
    fields:
      - name: 'title'
        label: 'Title'
        type: 'string'
        required: true
      
      - name: 'description'
        label: 'Description'
        type: 'text'
        required: true

      - name: 'updatedDate'
        label: 'Last Updated Date'
        type: 'date'
        required: true

      - name: 'metadata'
        label: 'Metadata'
        type: 'object'
        fields:
          - name: 'author'
            label: 'Author'
            type: 'string'
          - name: 'showInNav'
            label: 'Show in Navigation'
            type: 'boolean'

      - name: 'hero'
        label: 'Hero Section'
        type: 'object'
        fields:
          - name: 'title'
            label: 'Title'
            type: 'string'
          - name: 'description'
            label: 'Description'
            type: 'text'
          - name: 'backgroundImage'
            label: 'Background Image'
            type: 'image'

      - name: 'articlesSection'
        label: 'Articles Section'
        type: 'object'
        fields:
          - name: 'title'
            label: 'Title'
            type: 'string'
          - name: 'description'
            label: 'Description'
            type: 'text'
          - name: 'featuredTitle'
            label: 'Featured Title'
            type: 'string'
          - name: 'featuredDescription'
            label: 'Featured Description'
            type: 'text'
          - name: 'categoriesTitle'
            label: 'Categories Title'
            type: 'string'
          - name: 'categories'
            label: 'Categories'
            type: 'object'
            fields:
              - name: 'name'
                label: 'Category Name'
                type: 'string'
              - name: 'description'
                label: 'Category Description'
                type: 'text'
              - name: 'icon'
                label: 'Category Icon'
                type: 'string'

      - name: 'cta'
        label: 'Call to Action'
        type: 'object'
        fields:
          - name: 'title'
            label: 'Title'
            type: 'string'
          - name: 'description'
            label: 'Description'
            type: 'text'
          - name: 'buttonText'
            label: 'Button Text'
            type: 'string'
          - name: 'buttonUrl'
            label: 'Button URL'
            type: 'string'

      # SEO Fields
      - name: 'ogImage'
        label: 'OG Image'
        type: 'image'
      - name: 'ogType'
        label: 'OG Type'
        type: 'string'
      - name: 'twitterCard'
        label: 'Twitter Card'
        type: 'string'
      - name: 'metaRobots'
        label: 'Meta Robots'
        type: 'string'
      - name: 'keywords'
        label: 'Keywords'
        type: 'object'
      - name: 'author'
        label: 'Author'
        type: 'string'
