media:
  input: src/assets
  output: assets

content:
  - name: 'home'
    label: 'Home'
    type: 'file'
    path: 'src/content/pages/home.md'
    fields:
      - name: 'title'
        label: 'Title'
        type: 'string'
        required: true
      
      - name: 'description'
        label: 'Description'
        type: 'text'
        required: true

      - name: 'updatedDate'
        label: 'Last Updated Date'
        type: 'date'
        required: true

      - name: 'metadata'
        label: 'Metadata'
        type: 'object'
        fields:
          - name: 'author'
            label: 'Author'
            type: 'string'
          - name: 'showInNav'
            label: 'Show in Navigation'
            type: 'boolean'

      - name: 'hero'
        label: 'Hero Section'
        type: 'object'
        fields:
          - name: 'title'
            label: 'Title'
            type: 'string'
          - name: 'highlightedText'
            label: 'Highlighted Text'
            type: 'string'
          - name: 'description'
            label: 'Description'
            type: 'text'
          - name: 'primaryButtonText'
            label: 'Primary Button Text'
            type: 'string'
          - name: 'primaryButtonUrl'
            label: 'Primary Button URL'
            type: 'string'
          - name: 'secondaryButtonText'
            label: 'Secondary Button Text'
            type: 'string'
          - name: 'secondaryButtonUrl'
            label: 'Secondary Button URL'
            type: 'string'
          - name: 'backgroundImage'
            label: 'Background Image'
            type: 'image'
          - name: 'featureCard'
            label: 'Feature Card'
            type: 'object'
            fields:
              - name: 'title'
                label: 'Title'
                type: 'string'
              - name: 'features'
                label: 'Features'
                type: 'object'

      - name: 'about'
        label: 'About Section'
        type: 'object'
        fields:
          - name: 'title'
            label: 'Title'
            type: 'string'
          - name: 'description'
            label: 'Description'
            type: 'text'
          - name: 'mission'
            label: 'Mission'
            type: 'text'
          - name: 'missionImage'
            label: 'Mission Image'
            type: 'image'
          - name: 'values'
            label: 'Values'
            type: 'object'

      - name: 'services'
        label: 'Services Section'
        type: 'object'
        fields:
          - name: 'title'
            label: 'Title'
            type: 'string'
          - name: 'description'
            label: 'Description'
            type: 'text'
          - name: 'servicesList'
            label: 'Services List'
            type: 'object'

      - name: 'testimonials'
        label: 'Testimonials Section'
        type: 'object'
        fields:
          - name: 'title'
            label: 'Title'
            type: 'string'
          - name: 'description'
            label: 'Description'
            type: 'text'
          - name: 'testimonialsList'
            label: 'Testimonials List'
            type: 'object'

      - name: 'cta'
        label: 'Call to Action Section'
        type: 'object'
        fields:
          - name: 'title'
            label: 'Title'
            type: 'string'
          - name: 'description'
            label: 'Description'
            type: 'text'
          - name: 'buttonText'
            label: 'Button Text'
            type: 'string'
          - name: 'buttonUrl'
            label: 'Button URL'
            type: 'string'

      # SEO Fields
      - name: 'ogImage'
        label: 'OG Image'
        type: 'image'
      - name: 'ogType'
        label: 'OG Type'
        type: 'string'
      - name: 'twitterCard'
        label: 'Twitter Card'
        type: 'string'
      - name: 'metaRobots'
        label: 'Meta Robots'
        type: 'string'
      - name: 'keywords'
        label: 'Keywords'
        type: 'object'
      - name: 'author'
        label: 'Author'
        type: 'string'

  - name: 'about'
    label: 'About'
    type: 'file'
    path: 'src/content/pages/about.md'
    fields:
      - name: 'title'
        label: 'Title'
        type: 'string'
        required: true
      
      - name: 'description'
        label: 'Description'
        type: 'text'
        required: true

      - name: 'canonicalUrl'
        label: 'Canonical URL'
        type: 'string'

      - name: 'updatedDate'
        label: 'Last Updated Date'
        type: 'date'
        required: true

      - name: 'metadata'
        label: 'Metadata'
        type: 'object'
        fields:
          - name: 'author'
            label: 'Author'
            type: 'string'
          - name: 'showInNav'
            label: 'Show in Navigation'
            type: 'boolean'

      - name: 'pageHeader'
        label: 'Page Header'
        type: 'object'
        fields:
          - name: 'title'
            label: 'Title'
            type: 'string'
          - name: 'description'
            label: 'Description'
            type: 'text'

      - name: 'mission'
        label: 'Mission Section'
        type: 'object'
        fields:
          - name: 'imgSrc'
            label: 'Image Source'
            type: 'image'
          - name: 'imgAlt'
            label: 'Image Alt Text'
            type: 'string'
          - name: 'content'
            label: 'Content'
            type: 'text'

      - name: 'values'
        label: 'Values'
        type: 'object'
        fields:
          - name: 'title'
            label: 'Title'
            type: 'string'
          - name: 'description'
            label: 'Description'
            type: 'text'
          - name: 'icon'
            label: 'Icon'
            type: 'string'

      - name: 'founders'
        label: 'Founders'
        type: 'object'
        fields:
          - name: 'name'
            label: 'Name'
            type: 'string'
          - name: 'title'
            label: 'Title'
            type: 'string'
          - name: 'bio'
            label: 'Biography'
            type: 'text'
          - name: 'imgSrc'
            label: 'Image Source'
            type: 'image'
          - name: 'imgAlt'
            label: 'Image Alt Text'
            type: 'string'

      - name: 'cta'
        label: 'Call to Action'
        type: 'object'
        fields:
          - name: 'title'
            label: 'Title'
            type: 'string'
          - name: 'description'
            label: 'Description'
            type: 'text'
          - name: 'buttonText'
            label: 'Button Text'
            type: 'string'
          - name: 'buttonUrl'
            label: 'Button URL'
            type: 'string'

      # SEO Fields
      - name: 'ogImage'
        label: 'OG Image'
        type: 'image'
      - name: 'ogType'
        label: 'OG Type'
        type: 'string'
      - name: 'twitterCard'
        label: 'Twitter Card'
        type: 'string'
      - name: 'metaRobots'
        label: 'Meta Robots'
        type: 'string'
      - name: 'keywords'
        label: 'Keywords'
        type: 'object'
      - name: 'author'
        label: 'Author'
        type: 'string'
