media:
  input: src/assets
  output: assets

content:
  - name: 'home'
    label: 'Home'
    type: 'file'
    path: 'src/content/pages/home.md'
    format: 'md'
    fields:
      - name: 'title'
        label: 'Title'
        type: 'text'
        required: true
